// Attach to a chart in your MT5 DEMO account. Keep the GitHub token private.
#property strict
input string GitHubOwner="siddharthachaurasiyastarair-max";
input string GitHubRepository="Trade-Journal";
input string GitHubToken="PASTE_FINE_GRAINED_TOKEN_HERE";
string J(string s){StringReplace(s,"\\","\\\\");StringReplace(s,"\"","\\\"");StringReplace(s,"\n","\\n");return s;}
double EntryPrice(ulong positionId){if(!HistorySelectByPosition(positionId))return 0;for(int i=0;i<HistoryDealsTotal();i++){ulong d=HistoryDealGetTicket(i);if(d&&HistoryDealGetInteger(d,DEAL_ENTRY)==DEAL_ENTRY_IN)return HistoryDealGetDouble(d,DEAL_PRICE);}return 0;}
void SendClosedDeal(ulong ticket){if(!HistoryDealSelect(ticket))return;long type=HistoryDealGetInteger(ticket,DEAL_TYPE),entry=HistoryDealGetInteger(ticket,DEAL_ENTRY);if((type!=DEAL_TYPE_BUY&&type!=DEAL_TYPE_SELL)||(entry!=DEAL_ENTRY_OUT&&entry!=DEAL_ENTRY_OUT_BY))return;ulong position=(ulong)HistoryDealGetInteger(ticket,DEAL_POSITION_ID);double pnl=HistoryDealGetDouble(ticket,DEAL_PROFIT)+HistoryDealGetDouble(ticket,DEAL_COMMISSION)+HistoryDealGetDouble(ticket,DEAL_SWAP)+HistoryDealGetDouble(ticket,DEAL_FEE);string side=type==DEAL_TYPE_BUY?"Buy":"Sell",trade=StringFormat("{\"externalId\":\"%I64u\",\"symbol\":\"%s\",\"direction\":\"%s\",\"entry\":%.8f,\"exit\":%.8f,\"sl\":%.8f,\"target\":%.8f,\"volume\":%.2f,\"pnl\":%.2f,\"closedAt\":\"%s\"}",ticket,J(HistoryDealGetString(ticket,DEAL_SYMBOL)),side,EntryPrice(position),HistoryDealGetDouble(ticket,DEAL_PRICE),HistoryDealGetDouble(ticket,DEAL_SL),HistoryDealGetDouble(ticket,DEAL_TP),HistoryDealGetDouble(ticket,DEAL_VOLUME),pnl,TimeToString((datetime)HistoryDealGetInteger(ticket,DEAL_TIME),TIME_DATE|TIME_MINUTES|TIME_SECONDS)),body="{\"event_type\":\"mt5_closed_trade\",\"client_payload\":{\"trade\":"+trade+"}}";char data[],result[];string headers="Accept: application/vnd.github+json\r\nAuthorization: Bearer "+GitHubToken+"\r\nX-GitHub-Api-Version: 2022-11-28\r\nContent-Type: application/json\r\n",responseHeaders,url="https://api.github.com/repos/"+GitHubOwner+"/"+GitHubRepository+"/dispatches";StringToCharArray(body,data,0,WHOLE_ARRAY,CP_UTF8);int code=WebRequest("POST",url,headers,10000,data,result,responseHeaders);if(code!=204)Print("GitHub sync failed: ",code," ",CharArrayToString(result));}
int OnInit(){return INIT_SUCCEEDED;}
void OnTradeTransaction(const MqlTradeTransaction &transaction,const MqlTradeRequest &request,const MqlTradeResult &result){if(transaction.type==TRADE_TRANSACTION_DEAL_ADD)SendClosedDeal(transaction.deal);}
